name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - run: npm ci
      
      - uses: nrwl/nx-set-shas@v4

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - run: npx nx affected -t lint test build
      - run: npx nx affected --parallel 1 -t e2e-ci
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: dist/.playwright/apps/
          retention-days: 30